#!/bin/bash

set -o pipefail

ls -al $HOME/.tmux.conf 2>/dev/null | grep 20230905015107 >/dev/null
if [ $? -eq 0 ]; then
  echo "tmux config symlink already installed. ignoring."
  exit 1
fi
ls $HOME/.tmux.conf >/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
  mv $HOME/.tmux.conf $HOME/.tmux.conf.bak
fi
abspath=$(realpath zet/20230905015107/tmux.conf)
ln -s "$abspath" $HOME/.tmux.conf

