#!/bin/bash

# select install program
if which brew >/dev/null ; then
  installprog="brew install"
elif which apt-get >/dev/null ; then
  echo "selecting apt for installing prerequesites"
  if [ "$UID" -eq 0 ]; then
    installprog="apt-get install -y"
  else
    installprog="sudo apt-get install -y"
  fi
fi
echo $installprog

function install_it {
  if ! which $1 >/dev/null ; then
    echo Installing $1 from $2
    $installprog $2
  else
    echo $1 is installed
  fi
}

install_it vim vim
install_it git git # in docker, git is required
install_it make make # make is required to install some things
install_it tmux tmux
install_it gawk gawk
install_it fzf fzf
install_it realpath coreutils
install_it basename coreutils
install_it realpath realpath # if debian or ubuntu install realpath as well?
install_it jq jq
install_it curl curl
install_it wget wget
install_it lscpu util-linux
install_it pip3 python3-pip
install_it python3 python3
install_it ip iproute2
#install_it go golang

if ! which nvim >/dev/null; then
  echo no neovim
  install_it vim vim
else
  echo neovim is installed
fi

# i want xclip installed as a prerequesite on linux but not on mac os
if ! which pbclip; then
  echo "need to have xclip on this machine"
  install_it xclip xclip
fi
