#!/usr/bin/awk -f
BEGIN {
  system("cat prime-directive")
  print ""
  print "For context, the following is everything you have been asked so far in a markdown code snippet surrounded by three backticks:"
  print "```"
  system("cat history")
  print "```"
  print ""
  print "Here is the current question:"
}
{
  print
}
END {
}
