#!/bin/bash
# run from within root directory of repo
# install bat to /usr/bin/bat
# pick download url from github interactively

downloadurl=$(zet/20230905030303/github-latest-files https://github.com/jesseduffield/lazygit | \
  fzf --preview=lscpu "--prompt=select the version of bat for your cpu> " | \
  awk '{print $2}')
if [ -z "$downloadurl" ]; then
  exit 1
fi
wget $downloadurl
filename=$(ls lazygit_* | head -n 1)

# install it
echo "installing file $filename"
tar -xzvf "$filename"
sudo cp lazygit /usr/bin/
