#!/bin/bash

function splash {
  echo "Get list of files of latest release from github."
  echo "Parameter 1: github url"
  echo "Returns filename and url as tab separated values"
}

if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters" >/dev/stderr
    splash
    exit 1
fi
if [[ "$1" == "--help" ]]; then
  splash
  exit 1
fi
which jq >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  echo "jq required" >/dev/stderr
  exit 1
fi

githuburl="$1"
username=$(echo $githuburl | cut -d / -f 4)
reponame=$(echo $githuburl | cut -d / -f 5)

tagname=$(2>/dev/null curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/$username/$reponame/releases | jq -r '.[].tag_name' | head -n 1)

2>/dev/null curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/$username/$reponame/releases/tags/$tagname | jq -r '.assets[] | "\(.name)	\(.browser_download_url)"'
