#!/bin/bash

splashscreen="$ENVIRON_BASEPATH/zet/20230906032330/splash"
cols=$(stty size | awk '{print $2}')

if [ $cols -lt 70 ]; then
  splashscreen="$ENVIRON_BASEPATH/zet/20230906032330/splash-narrow"
fi

if which lolcat >/dev/null 2>/dev/null; then
  $ENVIRON_BASEPATH/zet/20230906050031/center-text "$splashscreen" | lolcat
else
  $ENVIRON_BASEPATH/zet/20230906050031/center-text "$splashscreen"
fi
