#!/bin/bash

$ENVIRON_BASEPATH/zet/20230912192810/fuzzy-search-markdown-content | \
  fzf \
    --delimiter $'\t' \
    --preview="bat --color=always --language=markdown {1}" \
    --preview-window=top \
    --with-nth=2,3 | \
    cut -d $'\t' -f 1 | \
    xargs -I{} nvim {}
