#!/bin/bash

$ENVIRON_BASEPATH/zet/20230912192810/fuzzy-search-markdown-content | \
  fzf -m \
    --delimiter $'\t' \
    --preview="echo {} | awk -F $'\\t' '{ system (\"bat --color=always --language=markdown \\x22\" \$1 \"\x22\" ) }'" \
    --preview-window=top \
    --with-nth=2,3 | \
    cut -d $'\t' -f 1 | \
    awk '
    BEGIN {
      cmd = "bat --color=always --paging=never --style=header-filename --language=md "
    }
    {
      gsub(/\042/,"\\\042")
      full = cmd "\042" $0 "\042"
      system(full)
    }
    '

