#!/bin/bash

$ENVIRON_BASEPATH/zet/20230912192810/fuzzy-search-markdown-content | \
  fzf -m \
    --delimiter $'\t' \
    --preview="bat --color=always --language=markdown {1}" \
    --preview-window=top \
    --with-nth=2,3 | \
    cut -d $'\t' -f 1 | \
    awk '
    BEGIN {
      cmd = "bat --color=always --paging=never --style=header-filename --language=md "
    }
    {
      gsub(/\042/,"\\\042")
      full = cmd "\042" $0 "\042"
      system(full)
    }
    '

# #--preview="$ENVIRON_BASEPATH/zet/20230912192810/markdown-search-preview" 
