# expect path to environment to be provided env variable ENVIRON_PATH

# export the path to this repo so scripts can find each other
if [ -z "$ENVIRON_PATH" ]; then # running from somewhere without the environment var, maybe vim
  if [ -d zet ]; then
    export ENVIRON_BASEPATH="."
  fi
else # running from bashrc
  export ENVIRON_BASEPATH="$ENVIRON_PATH"
  $ENVIRON_BASEPATH/zet/20230906032330/show-splash
fi

# configure EDITOR environment variable so sudoedit and fff work
if [ -z "$EDITOR" ]; then
  if which nvim >/dev/null ; then
    export EDITOR=nvim
  else
    export EDITOR=vim
  fi
fi

# Add this to your .bashrc, .zshrc or equivalent.
# Run 'fff' with 'f' or whatever you decide to name the function.
f() {
    fff "$@"
    cd "$(cat "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d")"
}

# turn bash prompt into vi edit with Esc
set -o vi

# productivity boost shortcuts
alias g=lazygit
alias dk='docker-killer'
alias v='fzf --preview="bat --color=always {}" | xargs -o -I{} $EDITOR {}'
alias t='tmux a -t $(tmux ls | fzf| cut -d ":" -f 1) || tmux'
alias a='sudo apt install -y $(apt list 2>/dev/null | fzf | cut -d '/' -f 1)'
alias c='cd $(find / -type d 2>/dev/null | fzf "--preview=ls -al {}")'
alias q=exit
if 2>&1 ls --help | grep 'time-style' 2>/dev/null >/dev/null; then
  alias ll='ls -haltr --color=auto --time-style=full-iso'
else
  alias ll='ls -haltr --color=always' # for mac os, color=auto does not work
fi
alias sess='tmux new -s'
alias http='python3 -m http.server'
alias bc='sudo bettercap -autostart events.stream,net.recon,net.sniff,net.probe,arp.spoof,any.proxy'

# scripts
alias k='search-markdown'
alias ke='edit-kb-fuzzy-find-markdown'

alias environ='cd $ENVIRON_BASEPATH && ./zkvr'
alias vars='$EDITOR ~/.variables.sh && source ~/.variables.sh'

if [ -d "$HOME/go/bin" ]; then
  export PATH="$PATH:$HOME/go/bin"
fi
export PATH="$PATH:$ENVIRON_BASEPATH/shortcuts"
if [ -f ~/.variables.sh ]; then
  source ~/.variables.sh
fi
