#!/bin/bash

if [ -z "$1" ]; then
  echo "need to provide the zk path"
  exit 1
fi
if [ -z "$2" ]; then
  echo "need to provide the github URL"
  exit 1
fi
zkpath="$1"
url="$2"
tf=$(mktemp -d)

git clone "$url" "$tf"

cd "$zkpath"
find . -type f -name '*.md' | sed 's_^\./__' | while read file; do
  dir=$(echo "$file" | awk 'BEGIN { FS = OFS = "/" } { NF--; print }')
  #echo "processing file $file in dir $dir"
  mkdir -p "$tf/$dir"
  cp "$zkpath/$file" "$tf/$file"
done

# debugging
#echo "cd $tf"
#exit 0

# copy in all the files
#cp -r "$zkpath" "$tf"
#cd "$tf"
# delete anything not markdown or git internal files
#find . -type f | grep -v '\.md$' | grep -v '\.git' | xargs -I{} rm {}

cd "$tf"

# if there's changes to commit
if [[ $(git status --porcelain | wc -l | awk '{print $1}') != "0" ]]; then
  git add .
  git commit -m 'syncing changes'
  git push
fi

cd - >/dev/null
rm -rf "$tf"
