#!/bin/bash

if which brew 2>/dev/null >/dev/null; then
  brew install fff # that was easy
  exit 0
fi
git clone https://github.com/dylanaraps/fff
cd fff
if [ "$UID" -eq 0 ]; then
  make install
else
  sudo make install
fi
cd ..
rm -rf fff
