#!/bin/bash

# install vimrc
# check if this version is already symlinked
if ls -al ~/.vimrc 2>/dev/null | grep 20230905015059 2>/dev/null >/dev/null ; then
  echo vimrc symlink is installed
else
  # install
  mv ~/.vimrc ~/vimrc.bak 2>/dev/null
  ln -s $(pwd)/zet/20230905015059/plainvimconfig.vim $HOME/.vimrc
fi
