#!/bin/bash

# install vimrc
# check if this version is already symlinked
if ls -al ~/.vimrc 2>/dev/null | grep 20230905015059 2>/dev/null >/dev/null ; then
  echo vimrc symlink is already installed
else
  # install
  mv ~/.vimrc ~/vimrc.bak 2>/dev/null
  ln -s $(pwd)/zet/20230905015059/plainvimconfig.vim $HOME/.vimrc
fi

if which nvim >/dev/null 2>/dev/null; then
  echo "installing neovim config"
  # initialize neovim config dir
  mkdir -p $HOME/.config/nvim
  neovimrc="$HOME/.config/nvim/init.vim"
  if ls -al "$neovimrc" 2>/dev/null | grep 20230905015059 >/dev/null; then
    echo "neovim config is already installed"
  else
    # nvim config is is zet/20230905015059/vimconfig.vim
    mv $neovimrc "$neovimrc.bak"
    ln -s $(pwd)/zet/20230905015059/vimconfig.vim $neovimrc
  fi

  if [ ! -d $HOME/.vim/bundle/Vundle.vim/.git ]; then
    echo "installing neovim plugin vundle"
    # set up vundle for neovim plugins
    git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
  else
    echo "neovim plugin vundle is already initialized"
  fi
  nvim -c ':PluginInstall' -c ':q' -c ':q'
fi
