#!/bin/bash

export MY_DIR="$2"
#export MY_ID=$(echo "$MY_DIR" | awk -F / '{print $NF}')
#export ZET_IMPL=20221006032546

echo "generating shortcuts..."
$MY_DIR/update-shortcuts
echo "shortcuts done."
