#!/bin/bash

# fixed with https://nickjanetakis.com/blog/using-dockers-v2-api-to-get-a-list-of-tags-with-the-help-of-jq
rep=$1

curl --silent \
    "https://registry.hub.docker.com/v2/repositories/library/${rep}/tags?page_size=1000" \
    | jq -r ".results[].name" | sort --version-sort
