#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -d .git ]; then
  git remote get-url $(git remote | head -n 1)
else
  echo "run in a git repository!"
  exit 1
fi
