#!/bin/bash

url="$1"

#if ! which youtube-dl >/dev/null; then
#  exit 1
#fi
#youtube-dl "$url"
#mv *.mkv video.mkv
srcfile="video.mkv"

if [ ! -f $srcfile ]; then
  mv *.mp4 video.mp4
  srcfile="video.mp4"
fi

source <(exiftool $srcfile | grep ^Duration | awk -F : '
/^Duration/ {
  print "seconds=" $NF
  print "minutes=" $(NF-1)
  print "hours=" ($(NF-2) + 1) - 1
} ')

for m in $(seq 0 $minutes); do
  if [ $m -lt $minutes ]; then
    sec=60
  else
    sec=$minutes
  fi
  for s in $(seq 0 $sec); do
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 00:$m:$s"
    ffmpeg -ss $m:$s -i $srcfile -frames 1 -s 1024x768 -f image2 image.png
    tesseract image.png output
    cat output.txt
    rm image.png
    rm output.txt
    sleep 1
  done
done
rm video.mkv
