#!/bin/bash

# input: one or more initial IDs to ship
# output: everything that needs shippin with it

allreferences=$(mktemp)
workingset=$(mktemp)
next=$(mktemp)
found=$(mktemp)

# take a set of all ids as references to search for
ls zet > $allreferences

# maintain a working set which is initially the input IDs
echo $1 >> $workingset
workingsetsize=$(wc -l $workingset | awk '{print $1}')

# loop while working set is not empty
while [[ $workingsetsize -gt 0 ]]; do
  # add working set to found
  cat $workingset >> $found
  echo > $next # clear out next references
  # grep the directories in working set for references.
  for id in $workingset; do
    # trim the grep output to just a list of unique IDs
    grep -Rof $allreferences zet/$id | grep -v 'README.md:' | cut -d : -f 2 >> $next
  done
  # take the references returned and subtract anything already in the results so we don't repeat IDs
  # those references become the next working set
  sort -u $next | grep -vf $found > $workingset
  workingsetsize=$(wc -l $workingset | awk '{print $1}')
done

rm "$allreferences"
rm "$workingset"
rm "$next"

# return found
cat $found
rm "$found"

