#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

#executable_files=$(mktemp)
#find zet -type f -executable | sort > "$executable_files"

directory=${1:-zet} # argument value or default

$SCRIPT_DIR/check-script-dependencies $( find $directory -type f -executable )
