#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# the search directory to start looking for related links.
# in order to actually work like obsidian, this should actually traverse back up to the top of the directory structure
searchdir=$(dirname "$1")

# TODO: this might not work if called from a shortcut? maybe it would if both scripts are there.
$SCRIPT_DIR/markdown-obsidian-links "$@" | while read line;
do
  find "$searchdir" -type f -name "$line*"
done
