#!/bin/bash
# find alphanumeric base64 using awk script
#- ` zet/20230906035744/space-invader `
echo "$1" | $ENVIRON_BASEPAH/zet/20230906035744/space-invader | while read line; do
  echo -n "$line" | base64 -w0
  echo ""
done | grep '^[A-Za-z0-9]*$'
