#!/bin/bash

echo installing environment
echo should run from base working directory of repository

# install prerequesite tools using package manager
zet/20230905184854/install-prerequisites

if which bat >/dev/null; then
  echo "bat is installed"
else
  zet/20230907151050/install-bat-interactive
fi
if which fff >/dev/null; then
  echo "fff is installed"
else
  zet/20230905210416/install-fff
fi

environ_path=$(pwd)
if ! grep "20230905015120" ~/.bashrc; then
  echo "installing into bashrc..."
  echo "ENVIRON_PATH=$environ_path source $environ_path/zet/20230905015120/bashrc" >> ~/.bashrc
else
  echo "already installed into bashrc"
fi
