#!/usr/bin/env python3
#https://www.python-boilerplate.com/flask

import os
from flask import Flask, jsonify, request
from flask_cors import CORS
import queue

mainQueue = queue.Queue()

def create_app(config=None):
    app = Flask(__name__)

    # See http://flask.pocoo.org/docs/latest/config/
    app.config.update(dict(DEBUG=True))
    app.config.update(config or {})

    # Setup cors headers to allow all domains
    # https://flask-cors.readthedocs.io/en/latest/
    CORS(app)

    # Definition of the routes. Put them into their own file. See also
    # Flask Blueprints: http://flask.pocoo.org/docs/latest/blueprints
    @app.route("/")
    def hello_world():
        return "This is a queue. Endpoints post /put, get /get"

    @app.route("/put", methods=["POST"])
    def putitem():
        d = request.get_data().decode('latin')
        mainQueue.put(d)
        return ""

    @app.route("/get")
    def getitem():
        return mainQueue.get()

    return app


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8000))
    app = create_app()
    app.run(host="0.0.0.0", port=port)
