#!/bin/bash

#xpup="go run github.com/ericchiang/xpup@latest"
url="$1"
tf=$(mktemp)
curl "$url" > $tf
stars=$(cat $tf | pup '#repo-stars-counter-star attr{title}' | sed 's/,//g')
echo "stars $stars"
echo "Last releases:"
cat $tf | pup 'div .text-small' | awk '/relative-time/,/\/relative-time/' | awk 'NR % 3 == 2'
rm "$tf"
