#!/bin/bash

mkdir /repo
cd /repo
git clone "$1" >/dev/null
dirname="$(ls)"

cd /secaudit/phpcs-security-audit
timeout 600 phpcs --extensions=php,inc,lib,module,info --standard=Security "/repo/$dirname"
